---
- name: Deploy Docker container
  hosts: webserver
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Docker image
      docker_image:
        name: nginx
        source: pull

    - name: Run Docker container
      docker_container:
        name: my_nginx
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "80:80"
